"""Add_Lumina_tables

Revision ID: 182f3ee31ba7
Revises: 001_initial
Create Date: 2026-01-20 17:26:49.713873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182f3ee31ba7'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lumina_deliverables',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lumina_deliverables_id'), 'lumina_deliverables', ['id'], unique=False)
    op.create_index(op.f('ix_lumina_deliverables_path'), 'lumina_deliverables', ['path'], unique=True)
    op.create_index(op.f('ix_lumina_deliverables_role'), 'lumina_deliverables', ['role'], unique=False)
    op.create_table('lumina_tasks',
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_id'], ['lumina_deliverables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lumina_tasks_deliverable_id'), 'lumina_tasks', ['deliverable_id'], unique=False)
    op.create_index(op.f('ix_lumina_tasks_id'), 'lumina_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sprints_number_key', 'sprints', ['number'])
    op.drop_index(op.f('ix_lumina_tasks_id'), table_name='lumina_tasks')
    op.drop_index(op.f('ix_lumina_tasks_deliverable_id'), table_name='lumina_tasks')
    op.drop_table('lumina_tasks')
    op.drop_index(op.f('ix_lumina_deliverables_role'), table_name='lumina_deliverables')
    op.drop_index(op.f('ix_lumina_deliverables_path'), table_name='lumina_deliverables')
    op.drop_index(op.f('ix_lumina_deliverables_id'), table_name='lumina_deliverables')
    op.drop_table('lumina_deliverables')
    # ### end Alembic commands ###
